In [30]:
import pandas as pd
import numpy as np

# statistics_maps = pd.read_csv('statistics_of_maps.txt', delimiter='&', names=['maps', 'dumper_f', 'fuel_f', 'time_f', 'score_f', 'dumper_1', 'fuel_1', 'time_1', 'score_1', 'fuel_2', 'time_2'])
statistics_maps = pd.read_csv('statistics_latex_format/scenario2.txt', delimiter='&', names=['maps', 'dumper_f', 'fuel_f', 'time_f', 'score_f', 'dumper_1', 'fuel_1', 'time_1', 'score_1', 'fuel_2', 'time_2'])

In [31]:
statistics_maps

,maps,dumper_f,fuel_f,time_f,score_f,dumper_1,fuel_1,time_1,score_1,fuel_2,time_2
0,1-a,23,634,6251,74.3,22,661,5369,74.0,483,4170
1,1-b,18,616,7836,73.4,14,629,7939,71.9,483,4170
2,2-a,16,396,5635,66.0,21,438,4068,65.6,265,3504
3,2-b,16,396,5635,66.0,14,423,5403,63.1,265,3504
4,3-a,16,728,7827,63.8,25,925,6104,55.3,488,3996
5,3-b,11,717,10723,61.9,14,884,9364,52.7,488,3996
6,4-a,25,674,6016,63.1,25,721,5770,60.3,423,3873
7,4-b,19,666,7412,61.3,25,721,5770,60.3,423,3873
8,5-a,19,484,6016,67.2,25,520,4076,68.7,337,3447
9,5-b,13,462,10735,64.8,14,494,6603,65.0,337,3447
10,6-a,25,465,5359,74.2,25,543,4553,68.0,351,3710
11,6-b,18,450,6531,73.7,20,539,5540,65.5,351,3710
12,7-a,19,553,5697,84.1,25,610,4392,81.3,492,3681
13,7-b,15,539,7432,82.9,13,582,6803,78.4,492,3681
14,8-a,23,546,6216,73.1,23,584,5155,71.8,412,3962
15,8-b,15,546,7630,70.7,15,571,8680,66.9,412,3962
16,9-a,25,493,5197,77.0,25,502,4047,79.5,395,3344
17,9-b,25,491,5373,76.8,21,500,4736,77.3,395,3344
18,10-a,12,442,7393,66.3,23,534,4374,64.0,308,3899
19,10-b,12,442,7975,65.6,11,473,7287,62.8,308,3899
20,11-a,14,654,8937,79.8,21,754,6517,74.0,573,4317
21,11-b,12,646,10142,79.5,12,719,10028,72.4,573,4317
22,12-a,25,668,6528,79.6,25,702,5585,78.5,559,4123
23,12-b,25,663,6994,79.3,20,700,6828,76.0,559,4123
24,13-a,8,409,9034,71.4,9,447,8342,66.9,316,4284
25,13-b,8,409,9034,71.4,9,447,8342,66.9,316,4284
26,14-a,25,451,5087,75.1,25,506,4524,70.0,352,3228
27,14-b,25,451,5087,75.1,25,506,4524,70.0,352,3228
28,15-a,14,436,6101,81.3,23,576,4340,69.5,377,3716
29,15-b,15,435,6347,81.0,10,525,8696,65.9,377,3716
30,16-a,12,515,7904,61.8,24,593,4477,62.8,333,3989
31,16-b,10,514,8959,60.7,11,531,8336,59.7,333,3989
32,17-a,25,718,5931,68.9,22,779,6124,64.1,499,3929
33,17-b,17,707,7530,66.9,16,777,7892,61.3,499,3929
34,18-a,25,472,4820,72.8,24,484,3888,74.6,349,3283
35,18-b,19,460,7100,69.9,20,481,4655,72.2,349,3283
36,19-a,18,480,5294,65.7,22,505,4320,65.9,320,3284
37,19-b,14,469,7136,63.8,13,492,6511,62.1,320,3284
38,20-a,25,579,6302,83.7,25,620,5206,81.7,515,3950
39,20-b,25,579,6302,83.7,25,620,5206,81.7,515,3950

In [32]:
print(f"Mean score, framework (a): {np.mean(statistics_maps['score_f'][::2]): 5.2f}")
print(f"Mean score, framework (b): {np.mean(statistics_maps['score_f'][1::2]) : 5.2f}")
print()
print(f"Mean score, benchmark 1 (a): {np.mean(statistics_maps['score_1'][::2]): 5.2f}")
print(f"Mean score, benchmark 1 (b): {np.mean(statistics_maps['score_1'][1::2]) : 5.2f}")

Mean score, framework (a):  72.46
Mean score, framework (b):  71.42

Mean score, benchmark 1 (a):  69.83
Mean score, benchmark 1 (b):  67.60

In [33]:
print(f"Mean fuel score, framework (a): {np.mean(statistics_maps['fuel_2'][::2]/statistics_maps['fuel_f'][::2]): 5.3f}")
print(f"Mean fuel score, framework (b): {np.mean(statistics_maps['fuel_2'][1::2]/statistics_maps['fuel_f'][1::2]): 5.3f}")

print()
print(f"Mean fuel score, framework (a): {np.mean(statistics_maps['fuel_2'][::2]/statistics_maps['fuel_1'][::2]): 5.3f}")
print(f"Mean fuel score, framework (b): {np.mean(statistics_maps['fuel_2'][1::2]/statistics_maps['fuel_1'][1::2]): 5.3f}")

Mean fuel score, framework (a):  0.755
Mean fuel score, framework (b):  0.764

Mean fuel score, framework (a):  0.681
Mean fuel score, framework (b):  0.703

In [34]:
print(f"Mean time score, framework (a): {np.mean(statistics_maps['time_2'][::2]/statistics_maps['time_f'][::2]): 5.3f}")
print(f"Mean time score, framework (b): {np.mean(statistics_maps['time_2'][1::2]/statistics_maps['time_f'][1::2]): 5.3f}")

print()
print(f"Mean time score, framework (a): {np.mean(statistics_maps['time_2'][::2]/statistics_maps['time_1'][::2]): 5.3f}")
print(f"Mean time score, framework (b): {np.mean(statistics_maps['time_2'][1::2]/statistics_maps['time_1'][1::2]): 5.3f}")

Mean time score, framework (a):  0.605
Mean time score, framework (b):  0.514

Mean time score, framework (a):  0.766
Mean time score, framework (b):  0.567

In [35]:
print(f"Mean dumper usage, framework (a): {np.mean(statistics_maps['dumper_f'][::2]): 5.2f}")
print(f"Mean dumper usage, framework (b): {np.mean(statistics_maps['dumper_f'][1::2]) : 5.2f}")
print()
print(f"Mean dumper usage, benchmark 1 (a): {np.mean(statistics_maps['dumper_1'][::2]): 5.2f}")
print(f"Mean dumper usage, benchmark 1 (b): {np.mean(statistics_maps['dumper_1'][1::2]) : 5.2f}")

Mean dumper usage, framework (a):  19.70
Mean dumper usage, framework (b):  16.60

Mean dumper usage, benchmark 1 (a):  22.95
Mean dumper usage, benchmark 1 (b):  16.10

In [36]:
print(f"Mean fuel, framework (a): {np.mean(statistics_maps['fuel_f'][::2]): 5.3f}")
print(f"Mean fuel, framework (b): {np.mean(statistics_maps['fuel_f'][1::2]): 5.3f}")

print()
print(f"Mean fuel, benchmark 1 (a): {np.mean(statistics_maps['fuel_1'][::2]): 5.3f}")
print(f"Mean fuel, benchmark 1 (b): {np.mean(statistics_maps['fuel_1'][1::2]): 5.3f}")

Mean fuel, framework (a):  539.850
Mean fuel, framework (b):  532.900

Mean fuel, benchmark 1 (a):  600.200
Mean fuel, benchmark 1 (b):  580.700

In [37]:
print(f"Mean time, framework (a): {np.mean(statistics_maps['time_f'][::2]): 5.3f}")
print(f"Mean time, framework (b): {np.mean(statistics_maps['time_f'][1::2]): 5.3f}")

print()
print(f"Mean time, benchmark 1 (a): {np.mean(statistics_maps['time_1'][::2]): 5.3f}")
print(f"Mean time, benchmark 1 (b): {np.mean(statistics_maps['time_1'][1::2]): 5.3f}")

Mean time, framework (a):  6377.250
Mean time, framework (b):  7595.650

Mean time, benchmark 1 (a):  5061.550
Mean time, benchmark 1 (b):  6957.150

In [38]:
print(551/600)

0.9183333333333333

In [39]:
print(5937/5061)

1.1730883224659159